// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieTicketBookingSystem.Data;

#nullable disable

namespace MovieTicketBookingSystem.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20260423070835_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MovieTicketBookingSystem.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("SeatsBooked")
                        .HasColumnType("int");

                    b.Property<int>("ShowId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BookingId");

                    b.HasIndex("MovieId");

                    b.HasIndex("ShowId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("MovieTicketBookingSystem.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieId"));

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MovieName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MovieId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Duration = 148,
                            Genre = "Sci-Fi",
                            MovieName = "Inception"
                        },
                        new
                        {
                            MovieId = 2,
                            Duration = 152,
                            Genre = "Action",
                            MovieName = "The Dark Knight"
                        },
                        new
                        {
                            MovieId = 3,
                            Duration = 169,
                            Genre = "Sci-Fi",
                            MovieName = "Interstellar"
                        },
                        new
                        {
                            MovieId = 4,
                            Duration = 195,
                            Genre = "Romance",
                            MovieName = "Titanic"
                        },
                        new
                        {
                            MovieId = 5,
                            Duration = 162,
                            Genre = "Sci-Fi",
                            MovieName = "Avatar"
                        });
                });

            modelBuilder.Entity("MovieTicketBookingSystem.Models.Show", b =>
                {
                    b.Property<int>("ShowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShowId"));

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ShowTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ShowId");

                    b.HasIndex("MovieId");

                    b.ToTable("Shows");

                    b.HasData(
                        new
                        {
                            ShowId = 1,
                            AvailableSeats = 100,
                            MovieId = 1,
                            ShowTime = new DateTime(2026, 4, 24, 10, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            ShowId = 2,
                            AvailableSeats = 100,
                            MovieId = 1,
                            ShowTime = new DateTime(2026, 4, 24, 14, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            ShowId = 3,
                            AvailableSeats = 150,
                            MovieId = 2,
                            ShowTime = new DateTime(2026, 4, 24, 11, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            ShowId = 4,
                            AvailableSeats = 150,
                            MovieId = 2,
                            ShowTime = new DateTime(2026, 4, 24, 18, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            ShowId = 5,
                            AvailableSeats = 120,
                            MovieId = 3,
                            ShowTime = new DateTime(2026, 4, 25, 12, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            ShowId = 6,
                            AvailableSeats = 120,
                            MovieId = 3,
                            ShowTime = new DateTime(2026, 4, 25, 20, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            ShowId = 7,
                            AvailableSeats = 200,
                            MovieId = 4,
                            ShowTime = new DateTime(2026, 4, 24, 16, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            ShowId = 8,
                            AvailableSeats = 200,
                            MovieId = 4,
                            ShowTime = new DateTime(2026, 4, 25, 15, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            ShowId = 9,
                            AvailableSeats = 180,
                            MovieId = 5,
                            ShowTime = new DateTime(2026, 4, 26, 13, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            ShowId = 10,
                            AvailableSeats = 180,
                            MovieId = 5,
                            ShowTime = new DateTime(2026, 4, 26, 19, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("MovieTicketBookingSystem.Models.Booking", b =>
                {
                    b.HasOne("MovieTicketBookingSystem.Models.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieTicketBookingSystem.Models.Show", "Show")
                        .WithMany("Bookings")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Show");
                });

            modelBuilder.Entity("MovieTicketBookingSystem.Models.Show", b =>
                {
                    b.HasOne("MovieTicketBookingSystem.Models.Movie", "Movie")
                        .WithMany("Shows")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieTicketBookingSystem.Models.Movie", b =>
                {
                    b.Navigation("Shows");
                });

            modelBuilder.Entity("MovieTicketBookingSystem.Models.Show", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
